#!/bin/sh

# NOTE: this script will download plugins with specific versions
# If some package is unavailable at the time you use the script,
# just find another source and substitute it

curdir=$(basename $(pwd))
if [ $curdir != ".emacs.d" ] ; then
    echo "Please run install in directory ~/.emacs.d"
    exit
fi

mkdir -pv plugins
cd plugins

mkdir -pv misc
cd misc

if [ ! -e "window-numbering.el" ] ; then
    wget http://nschum.de/src/emacs/window-numbering-mode/window-numbering.el
fi

if [ ! -e "autopair.el" ] ; then
    wget http://autopair.googlecode.com/svn/trunk/autopair.el
fi

if [ ! -e "graphviz-dot-mode.el" ] ; then
    wget http://users.skynet.be/ppareit/projects/graphviz-dot-mode/graphviz-dot-mode.el
fi

if [ ! -e "linum+.el" ] ; then
    wget http://www.emacswiki.org/emacs/download/linum+.el
fi

if [ ! -e "quick-jump.el" ] ; then
    wget http://www.emacswiki.org/emacs/download/quick-jump.el
fi

if [ ! -e "dired+.el" ] ; then
    wget http://www.emacswiki.org/emacs/download/dired+.el
fi

if [ ! -e "xcscope.el" ] ; then
    wget http://inst.eecs.berkeley.edu/~cs186/fa05/debugging/xcscope.el
fi

cd ..

mkdir -pv zjl-hl #extended c/c++/elisp highlights
cd zjl-hl
if [ ! -e "zjl-hl.el" ] ; then
    wget http://www.emacswiki.org/emacs/download/zjl-hl.el
fi
if [ ! -e "highlight.el" ] ; then
    wget http://www.emacswiki.org/emacs/download/highlight.el
fi
if [ ! -e "region-list-edit.el" ] ; then
    wget http://www.emacswiki.org/emacs/download/region-list-edit.el
fi
cd ..

mkdir -pv color-theme
cd color-theme
if [ ! -e "color-theme-6.6.0.tar.gz" ] ; then
    wget http://download.savannah.gnu.org/releases/color-theme/color-theme-6.6.0.tar.gz
    tar -zxvf color-theme-6.6.0.tar.gz
fi
if [ ! -e "color-theme-tangotango" ] ; then
    git clone https://github.com/juba/color-theme-tangotango.git
fi
cd ..

if [ ! -e "yasnippet" ] ; then
    git clone https://github.com/capitaomorte/yasnippet
fi

mkdir -pv ibus
cd ibus
if [ ! -e "ibus-el-0.2.1.tar.gz" ] ; then
     wget http://launchpad.net/ibus.el/0.2/0.2.1/+download/ibus-el-0.2.1.tar.gz
     tar -zvxf ibus-el-0.2.1.tar.gz
fi 
cd ..

mkdir -pv cedet
cd cedet
if [ ! -e "cedet-1.0.1.tar.gz" ] ; then
    wget http://sourceforge.net/projects/cedet/files/cedet/cedet-1.0.1.tar.gz
     tar -zvxf cedet-1.0.1.tar.gz
     cd cedet-1.0.1
     make
     cd ..
fi 
cd ..

mkdir -pv ecb
cd ecb
if [ ! -e ecb-2.40.tar.gz ] ; then
    wget http://sourceforge.net/projects/ecb/files/ecb/ECB%202.40/ecb-2.40.tar.gz
    tar -zvxf ecb-2.40.tar.gz
fi
cd ..

mkdir -pv org-mode
cd org-mode
if [ ! -e "org-7.8.03.tar.gz" ] ; then
     wget http://orgmode.org/org-7.8.03.tar.gz
     tar -zxvf org-7.8.03.tar.gz
     cd org-7.8.03
     make
     cd ../../misc
     if [ ! -e "plantuml.jar" ] ; then
         wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/
     fi
     cd -
     cd ..
fi 
cd ..

if [ ! -e "hideshow-org" ] ; then
    git clone git://github.com/secelis/hideshow-org.git
fi

mkdir -pv auctex
cd auctex
if [ ! -e "auctex-11.86.tar.gz" ] ; then
    wget http://ftp.gnu.org/pub/gnu/auctex/auctex-11.86.tar.gz
    tar -zxvf auctex-11.86.tar.gz
    cd auctex-11.86
    ./configure
    make
    cd ..
fi
cd ..

mkdir -pv auto-complete
cd auto-complete
if [ ! -e "auto-complete-1.3.1.tar.bz2" ] ; then
    wget http://cx4a.org/pub/auto-complete/auto-complete-1.3.1.tar.bz2
    tar -jxvf auto-complete-1.3.1.tar.bz2
    cd auto-complete-1.3.1
    make byte-compile
    cd ..
fi
cd ..

cd .. # now in ~/.emacs.d/

# set patch to "y" if you want to apply patch
doPatch="n"
if [ $doPatch = y ] ; then
    patch -p0 < ./patch/xcscope.patch
    patch -p0 < ./patch/color-theme-tangotango.patch
    patch -p0 < ./patch/zjl-hl.patch
fi
